### ISSUE TITLE
CMake is garbage

### ISSUE THREAD

**Issue by gufoe** [uWebSockets/uWebSockets#353]
Hello, I'm having trouble installing on debian jessie release.
 
```
# uname -a
Linux home 2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 x86_64 GNU/Linux
```

```
jake@home:/tmp$ git clone https://github.com/uWebSockets/uWebSockets.git && cd uWebSockets
Cloning into 'uWebSockets'...
remote: Counting objects: 2885, done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 2885 (delta 32), reused 0 (delta 0), pack-reused 2828
Receiving objects: 100% (2885/2885), 851.57 KiB | 1.23 MiB/s, done.
Resolving deltas: 100% (1779/1779), done.
Checking connectivity... done.
```
```
jake@home:/tmp/uWebSockets$ cmake .
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1t") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/uWebSockets
```
```
jake@home:/tmp/uWebSockets$ make
Scanning dependencies of target uWS
[  9%] Building CXX object CMakeFiles/uWS.dir/src/Extensions.cpp.o
In file included from /tmp/uWebSockets/src/Extensions.cpp:1:0:
/tmp/uWebSockets/src/Extensions.h:8:25: warning: scoped enums only available with -std=c++11 or -std=gnu++11
 enum Options : unsigned int {
                         ^
/tmp/uWebSockets/src/Extensions.cpp:15:24: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     int *lastInteger = nullptr;
                        ^
/tmp/uWebSockets/src/Extensions.cpp:18:30: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     bool perMessageDeflate = false;
                              ^
/tmp/uWebSockets/src/Extensions.cpp:19:36: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     bool serverNoContextTakeover = false;
                                    ^
/tmp/uWebSockets/src/Extensions.cpp:20:36: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     bool clientNoContextTakeover = false;
                                    ^
/tmp/uWebSockets/src/Extensions.cpp:21:31: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     int serverMaxWindowBits = 0;
                               ^
/tmp/uWebSockets/src/Extensions.cpp:22:31: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     int clientMaxWindowBits = 0;
                               ^
/tmp/uWebSockets/src/Extensions.cpp:15:24: error: 'nullptr' was not declared in this scope
     int *lastInteger = nullptr;
                        ^
/tmp/uWebSockets/src/Extensions.cpp: In member function 'std::string uWS::ExtensionsNegotiator<isServer>::generateOffer()':
/tmp/uWebSockets/src/Extensions.cpp:86:19: error: 'Options' is not a class or namespace
     if (options & Options::PERMESSAGE_DEFLATE) {
                   ^
/tmp/uWebSockets/src/Extensions.cpp:89:23: error: 'Options' is not a class or namespace
         if (options & Options::CLIENT_NO_CONTEXT_TAKEOVER) {
                       ^
/tmp/uWebSockets/src/Extensions.cpp:93:23: error: 'Options' is not a class or namespace
         if (options & Options::SERVER_NO_CONTEXT_TAKEOVER) {
                       ^
CMakeFiles/uWS.dir/build.make:54: recipe for target 'CMakeFiles/uWS.dir/src/Extensions.cpp.o' failed
make[2]: *** [CMakeFiles/uWS.dir/src/Extensions.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/uWS.dir/all' failed
make[1]: *** [CMakeFiles/uWS.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by alexhultman** [comment]
This is CMake not adding -std=c++11, which it should. CMake is garbage and should never be used. You can use the Makefile shipped with the library to properly compile the library on Unix systems (Linux only right now). Or, you can see if you can tinker with the piece of garbage CMake shit file to get it to work. I hate CMake.

**Comment by HongjiaLiu** [comment]
@gufoe Same error, while I'm compile it on my Rasperry Pi... Just forget the CMkae and try to use the Makefile

`make Linux`
`sudo make install`

done!

**Comment by alexhultman** [comment]
Yep, and you can even just type "make" (it will automatically select right line based on system)

**Comment by qwename** [comment]
I think the problem here is this line in CMakeLists.txt:
```
set(CMAKE_CXX_STANDARD 11)
```
From cmake's documentation for [CMAKE_CXX_STANDARD](https://cmake.org/cmake/help/v3.6/variable/CMAKE_CXX_STANDARD.html) and [CXX_STANDARD](https://cmake.org/cmake/help/v3.6/prop_tgt/CXX_STANDARD.html) you can see that these are not variables, but properties. The example given in the docs can be adapted to give:
```
# Add this after the line add_library(uWS ...)
set_property(TARGET uWS CMAKE_CXX_STANDARD 11)
```
As my compiler versions are newer, I did not have to change anything, but you can try it for yourself.

To avoid cluttering the root directory with CMake files, I suggest creating a `build` directory and performing your build there. This way, you can edit CMakeLists.txt and make a different build based on that.

Without CMakeLists.txt modification:
```
[qwename@logo uWebSockets]$ pwd
/home/qwename/lib/uWebSockets
[qwename@logo uWebSockets]$ mkdir build
[qwename@logo uWebSockets]$ cd build/
[qwename@logo build]$ cmake ..
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2j")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qwename/lib/uWebSockets/build
[qwename@logo build]$ make
Scanning dependencies of target uWS
[  7%] Building CXX object CMakeFiles/uWS.dir/src/Extensions.cpp.o
[ 14%] Building CXX object CMakeFiles/uWS.dir/src/Group.cpp.o
[ 21%] Building CXX object CMakeFiles/uWS.dir/src/WebSocketImpl.cpp.o
[ 28%] Building CXX object CMakeFiles/uWS.dir/src/Networking.cpp.o
[ 35%] Building CXX object CMakeFiles/uWS.dir/src/Hub.cpp.o
[ 42%] Building CXX object CMakeFiles/uWS.dir/src/Node.cpp.o
[ 50%] Building CXX object CMakeFiles/uWS.dir/src/WebSocket.cpp.o
[ 57%] Building CXX object CMakeFiles/uWS.dir/src/HTTPSocket.cpp.o
[ 64%] Building CXX object CMakeFiles/uWS.dir/src/Socket.cpp.o
[ 71%] Linking CXX shared library libuWS.so
[ 71%] Built target uWS
Scanning dependencies of target echo
[ 78%] Building CXX object examples/CMakeFiles/echo.dir/echo.cpp.o
[ 85%] Linking CXX executable echo
[ 85%] Built target echo
Scanning dependencies of target multithreaded_echo
[ 92%] Building CXX object examples/CMakeFiles/multithreaded_echo.dir/multithreaded_echo.cpp.o
[100%] Linking CXX executable multithreaded_echo
[100%] Built target multithreaded_echo
```
With CMakeLists.txt modification:
```
[qwename@logo uWebSockets]$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1fadf72..5974d9e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,5 @@
 cmake_minimum_required(VERSION 3.0)
 set(CMAKE_BUILD_TYPE Release)
-set(CMAKE_CXX_STANDARD 11)
 if(CMAKE_VERSION VERSION_LESS "3.1")
     # CMake 3.0 does not implement "CMAKE_CXX_STANDARD":
     if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
@@ -22,6 +21,7 @@ if(NOT LIBUV_LIBRARY)
 endif()

 add_library(uWS src/Extensions.cpp src/Group.cpp src/WebSocketImpl.cpp src/Networking.cpp src/Hub.cpp src/Node.cpp src/WebSocket.cpp src/HTTPSocket.cpp src/Socket.cpp)
+set_property(TARGET uWS PROPERTY CMAKE_CXX_STANDARD 11)
 target_include_directories(uWS PUBLIC src)

 target_include_directories(uWS PUBLIC ${LIBUV_INCLUDE_DIR})
[qwename@logo uWebSockets]$ mkdir build2
[qwename@logo uWebSockets]$ cd build2
[qwename@logo build2]$ cmake ..
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2j")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qwename/lib/uWebSockets/build2
[qwename@logo build2]$ make
Scanning dependencies of target uWS
[  7%] Building CXX object CMakeFiles/uWS.dir/src/Extensions.cpp.o
[ 14%] Building CXX object CMakeFiles/uWS.dir/src/Group.cpp.o
[ 21%] Building CXX object CMakeFiles/uWS.dir/src/WebSocketImpl.cpp.o
[ 28%] Building CXX object CMakeFiles/uWS.dir/src/Networking.cpp.o
[ 35%] Building CXX object CMakeFiles/uWS.dir/src/Hub.cpp.o
[ 42%] Building CXX object CMakeFiles/uWS.dir/src/Node.cpp.o
[ 50%] Building CXX object CMakeFiles/uWS.dir/src/WebSocket.cpp.o
[ 57%] Building CXX object CMakeFiles/uWS.dir/src/HTTPSocket.cpp.o
[ 64%] Building CXX object CMakeFiles/uWS.dir/src/Socket.cpp.o
[ 71%] Linking CXX shared library libuWS.so
[ 71%] Built target uWS
Scanning dependencies of target echo
[ 78%] Building CXX object examples/CMakeFiles/echo.dir/echo.cpp.o
[ 85%] Linking CXX executable echo
[ 85%] Built target echo
Scanning dependencies of target multithreaded_echo
[ 92%] Building CXX object examples/CMakeFiles/multithreaded_echo.dir/multithreaded_echo.cpp.o
[100%] Linking CXX executable multithreaded_echo
[100%] Built target multithreaded_echo
```

**Comment by gufoe** [comment]
Just tried and it's not working, I applied your patch to a fresh clone, still the same error.
I have cmake v. 3.0.2 and g++ v. 4.9.2.

**Comment by qwename** [comment]
Note that the `CXX_STANDARD` property only works for cmake version 3.1 and above.

Try this instead:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1fadf72..200a746 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,12 +1,5 @@
 cmake_minimum_required(VERSION 3.0)
 set(CMAKE_BUILD_TYPE Release)
-set(CMAKE_CXX_STANDARD 11)
-if(CMAKE_VERSION VERSION_LESS "3.1")
-    # CMake 3.0 does not implement "CMAKE_CXX_STANDARD":
-    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
-        set(CMAKE_CXX_FLAGS "--std=gnu++11 ${CMAKE_CXX_FLAGS}")
-    endif()
-endif()
 project (µWebSockets)
 
 option(BUILD_SHARED_LIBS "Build shared libraries." ON)
@@ -22,6 +15,14 @@ if(NOT LIBUV_LIBRARY)
 endif()
 
 add_library(uWS src/Extensions.cpp src/Group.cpp src/WebSocketImpl.cpp src/Networking.cpp src/Hub.cpp src/Node.cpp src/WebSocket.cpp src/HTTPSocket.cpp src/Socket.cpp)
+if(CMAKE_VERSION VERSION_LESS "3.1")
+    # CMake 3.0 does not implement "CMAKE_CXX_STANDARD":
+    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
+        set(CMAKE_CXX_FLAGS "--std=gnu++11 ${CMAKE_CXX_FLAGS}")
+    endif()
+else()
+    set_property(TARGET uWS PROPERTY CMAKE_CXX_STANDARD 11)
+endif()
 target_include_directories(uWS PUBLIC src)
 
 target_include_directories(uWS PUBLIC ${LIBUV_INCLUDE_DIR})
```
Can you also give the output of `find ./CMakeFiles/ -type f -print0 | xargs -0 grep std=gnu` after running `cmake`?

**Comment by gufoe** [comment]
Yes that works! Here's the output anyway:
```
$ find ./CMakeFiles/ -type f -print0 | xargs -0 grep std=gnu
./CMakeFiles/uWS.dir/flags.make:CXX_FLAGS = --std=gnu++11  -fPIC -I/root/uWebSockets/src   
./CMakeFiles/uWS.dir/link.txt:/usr/bin/c++  -fPIC --std=gnu++11    -shared -Wl,-soname,libuWS.so -o libuWS.so CMakeFiles/uWS.dir/src/Extensions.cpp.o CMakeFiles/uWS.dir/src/Group.cpp.o CMakeFiles/uWS.dir/src/WebSocketImpl.cpp.o CMakeFiles/uWS.dir/src/Networking.cpp.o CMakeFiles/uWS.dir/src/Hub.cpp.o CMakeFiles/uWS.dir/src/Node.cpp.o CMakeFiles/uWS.dir/src/WebSocket.cpp.o CMakeFiles/uWS.dir/src/HTTPSocket.cpp.o CMakeFiles/uWS.dir/src/Socket.cpp.o -luv -lssl -lcrypto -lz -lpthread 
```

Will you apply the patch to the repo?

**Comment by qwename** [comment]
Probably not since issue #354 is about removing CMake, and @alexhultman seems to hate it.

**Comment by jcelerier** [comment]
If anyone want an up-to-date CMakeLists.txt for the sake of integrating uWebSockets in other software, I made one here : https://github.com/jcelerier/uWebSockets/blob/9b44409c8e5388eef47a8de1ed486146b9ba9ce4/CMakeLists.txt
